# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

# Régler ici les conditions du déclenchement du CICD
on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Ajouter les versions de NodeJS sur lesquels tester
        node-version: [16.x]
        # Pour voir les versions de NodeJS: https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    # npm run build dépend de la config du package.json
    - run: npm run build --if-present
    # npm test dépend de la config du package.json
    - run:  CI=true npm test -- --coverage
